version: "3.8"


services:
 postgres:
   image: postgres:13
   container_name: airflow_postgres
   environment:
     POSTGRES_USER: airflow
     POSTGRES_PASSWORD: airflow
     POSTGRES_DB: airflow
   volumes:
     - postgres-db:/var/lib/postgresql/data


 airflow:
   image: apache/airflow:2.11.0
   container_name: airflow
   depends_on:
     - postgres
   environment:
     AIRFLOW__CORE__EXECUTOR: LocalExecutor
     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     AIRFLOW__CORE__LOAD_EXAMPLES: "false"
     AIRFLOW__WEBSERVER__SECRET_KEY: my_secret_key
   volumes:
     - ./dags:/opt/airflow/dags
     - ./logs:/opt/airflow/logs
     - ./plugins:/opt/airflow/plugins
   ports:
     - "8080:8080"
   command: >
     bash -c "
     airflow db init &&
     airflow users create \
       --username airflow \
       --password airflow \
       --firstname Air \
       --lastname Flow \
       --role Admin \
       --email airflow@example.com || true &&
     airflow webserver & airflow scheduler
     "
   restart: always
 mysql:
   image: mysql:8.0
   container_name: mysql-db
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root123
     MYSQL_DATABASE: demo_db
     MYSQL_USER: demo_user
     MYSQL_PASSWORD: demo123
   ports:
     - "3306:3306"
   volumes:
     - mysql_data:/var/lib/mysql

volumes:
 postgres-db:
 mysql_data:
